
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-movie
    restart: always
    ports:
      - "3306:3306"  # 호스트의 3306 포트와 컨테이너의 3306 포트 연결
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # MySQL root 계정 비밀번호
      MYSQL_DATABASE: dev_database         # 생성할 데이터베이스 이름
      MYSQL_USER: dev_user                 # 사용자 계정 이름
      MYSQL_PASSWORD: dev_password         # 사용자 계정 비밀번호
      TZ: Asia/Seoul                       # 시간대 설정 (KST로 설정)
    volumes:
      - mysql_data:/var/lib/mysql          # 데이터 영구 저장 (볼륨 사용)
    command:
      - --character-set-server=utf8mb4         # 인코딩 규칙 (유니코드 4바이트 지원)
      - --collation-server=utf8mb4_unicode_ci  # 정렬 규칙 (case insensitive)

volumes:
  mysql_data:                              # 데이터가 유지될 볼륨 정의
