spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_database
      ?useUnicode=true
      &characterEncoding=UTF-8
      &serverTimezone=Asia/Seoul
      &useSSL=false
      &allowPublicKeyRetrieval=true
    username: dev_user
    password: dev_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL 실행하지 않음
    show-sql: true
    defer-datasource-initialization: true # JPA 엔티티 초기화 이후 data.sql을 실행
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: Asia/Seoul
        connection.characterEncoding: UTF-8
        connection.useUnicode: true
        connection.collation: utf8mb4_unicode_ci
        format_sql: true  # SQL 보기 좋게 출력

  sql.init.mode: never  # Spring의 schema.sql 및 data.sql 실행 방지
  sql.init.schema-locations: classpath:v1.0__initial_schema.sql
  sql.init.data-locations: classpath:data.sql

logging:
  level:
    org.hibernate.sql: DEBUG                   # SQL 쿼리 로깅
    org.hibernate.orm.jdbc.bind: TRACE         # SQL 바인딩 파라미터 로깅
    org.hibernate.type.descriptor.sql: TRACE   # SQL 파라미터 값 로깅
    org.springframework.transaction.interceptor: DEBUG  # 트랜잭션 정보
